import photo1 from '../utils/Pictures/1.jpg'
import photo2 from '../utils/Pictures/2.jpg'
import photo3 from '../utils/Pictures/3.jpg'
import photo4 from '../utils/Pictures/4.jpg'
import photo5 from '../utils/Pictures/5.jpg'
import photo6 from '../utils/Pictures/6.jpg'
import photo7 from '../utils/Pictures/7.jpg'
import photo8 from '../utils/Pictures/8.jpg'
import photo9 from '../utils/Pictures/9.jpg'
import photo10 from '../utils/Pictures/10.jpg'

